-- Reconcile pre-existing migration-history drift (Note/Project/Task table
-- definitions diverged from schema.prisma over time). Data-preserving
-- SQLite table rebuilds generated by 'prisma migrate diff'.
PRAGMA foreign_keys=OFF;
-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Note" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "projectId" TEXT,
    "taskId" TEXT,
    "createdById" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "tags" TEXT NOT NULL DEFAULT '[]',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Note_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Note_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Note_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Note_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_Note" ("body", "createdAt", "createdById", "id", "projectId", "tags", "taskId", "updatedAt", "workspaceId") SELECT "body", "createdAt", "createdById", "id", "projectId", "tags", "taskId", "updatedAt", "workspaceId" FROM "Note";
DROP TABLE "Note";
ALTER TABLE "new_Note" RENAME TO "Note";
CREATE INDEX "Note_workspaceId_projectId_idx" ON "Note"("workspaceId", "projectId");
CREATE INDEX "Note_createdById_workspaceId_idx" ON "Note"("createdById", "workspaceId");
CREATE INDEX "Note_taskId_idx" ON "Note"("taskId");
CREATE TABLE "new_Project" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" TEXT NOT NULL DEFAULT 'other',
    "mode" TEXT NOT NULL DEFAULT 'progress',
    "createdAt" DATETIME NOT NULL,
    "updatedAt" DATETIME NOT NULL,
    "startDate" DATETIME,
    "workspaceId" TEXT NOT NULL,
    CONSTRAINT "Project_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_Project" ("createdAt", "description", "id", "name", "startDate", "type", "updatedAt", "workspaceId") SELECT "createdAt", "description", "id", "name", "startDate", "type", "updatedAt", "workspaceId" FROM "Project";
DROP TABLE "Project";
ALTER TABLE "new_Project" RENAME TO "Project";
CREATE INDEX "Project_workspaceId_idx" ON "Project"("workspaceId");
CREATE TABLE "new_Task" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "estimateO" INTEGER NOT NULL,
    "estimateM" INTEGER NOT NULL,
    "estimateP" INTEGER NOT NULL,
    "size" TEXT NOT NULL DEFAULT 'm',
    "intensity" INTEGER,
    "confidence" REAL,
    "priority" INTEGER NOT NULL,
    "labels" TEXT,
    "assignee" TEXT,
    "startPlanned" DATETIME,
    "endPlanned" DATETIME,
    "startedAt" DATETIME,
    "finishedAt" DATETIME,
    "focusedAt" DATETIME,
    "blockedAt" DATETIME,
    "dueSoft" DATETIME,
    "dueHard" DATETIME,
    "timeframeBucket" TEXT,
    "timeframeAnchor" DATETIME,
    "milestoneId" TEXT,
    "parentTaskId" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Task_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Task_milestoneId_fkey" FOREIGN KEY ("milestoneId") REFERENCES "Milestone" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Task_parentTaskId_fkey" FOREIGN KEY ("parentTaskId") REFERENCES "Task" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Task" ("assignee", "blockedAt", "confidence", "createdAt", "dueHard", "dueSoft", "endPlanned", "estimateM", "estimateO", "estimateP", "finishedAt", "id", "intensity", "labels", "milestoneId", "notes", "parentTaskId", "priority", "projectId", "size", "startPlanned", "startedAt", "status", "timeframeAnchor", "timeframeBucket", "title", "type", "updatedAt") SELECT "assignee", "blockedAt", "confidence", "createdAt", "dueHard", "dueSoft", "endPlanned", "estimateM", "estimateO", "estimateP", "finishedAt", "id", "intensity", "labels", "milestoneId", "notes", "parentTaskId", "priority", "projectId", "size", "startPlanned", "startedAt", "status", "timeframeAnchor", "timeframeBucket", "title", "type", "updatedAt" FROM "Task";
DROP TABLE "Task";
ALTER TABLE "new_Task" RENAME TO "Task";
CREATE INDEX "Task_projectId_idx" ON "Task"("projectId");
CREATE INDEX "Task_parentTaskId_idx" ON "Task"("parentTaskId");
CREATE INDEX "Task_projectId_status_idx" ON "Task"("projectId", "status");
CREATE INDEX "Task_projectId_parentTaskId_idx" ON "Task"("projectId", "parentTaskId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

PRAGMA foreign_keys=ON;
